### ISSUE TITLE
[BUG] connector update API to update parameter got illegal_argument_exception when "actions.url" has a reference on parameter

### ISSUE THREAD

**Issue by chishui** [opensearch-project/ml-commons#2502] opened 2024-06-05 09:50 UTC
**What is the bug?**
I created a connector with payload below
```
{
    "name": "OpenAI embedding Connector",
    "description": "The connector to public OpenAI model service for GPT 3.5",
    "version": 1,
    "protocol": "http",
    "parameters": {
        "endpoint": "api.openai.com",
        "auth": "API_Key",
        "content_type": "application/json",
        "max_tokens": 7,
        "temperature": 0,
        "model": "text-embedding-ada-002"
    },
    "actions": [
        {
            "action_type": "predict",
            "method": "POST",
            "url": "https://${parameters.endpoint}/v1/embeddings",
            "pre_process_function": "connector.pre_process.openai.embedding",
            "post_process_function": "connector.post_process.openai.embedding",
            "headers": {
                "Authorization": "Bearer ${credential.openAI_key}"
            },
            "request_body": "{ \"model\": \"${parameters.model}\", \"input\": ${parameters.input}}"
        }
    ]
}
```

Then I call connector update API below to update `temperature` field in parameters
```
{	
	"parameters": {
		"temperature": 3
	}
}
```
I get an exception:
```
{
	"error": {
		"root_cause": [
			{
				"type": "illegal_argument_exception",
				"reason": "Connector URL is not matching the trusted connector endpoint regex, URL is: https://${parameters.endpoint}/v1/embeddings"
			}
		],
		"type": "illegal_argument_exception",
		"reason": "Connector URL is not matching the trusted connector endpoint regex, URL is: https://${parameters.endpoint}/v1/embeddings"
	},
	"status": 400
}
```
It worked well if I created the connector with url directly configured not through parameters `"url": "https://api.openai.com/v1/embeddings",` 

I think it fails [this validation](https://github.com/opensearch-project/ml-commons/blob/9aea9a08ef2d9eba082bc34382a8a04c1cc5bffa/plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java#L94) because the parameters payload in the update API doesn't include endpoint.

**How can one reproduce the bug?**
Check bug description

**What is the expected behavior?**
I'm wondering what the expected behavior is when the update API only includes one attribute in parameters, should it overwrite the whole `parameters` field or it should merge with existing `parameters` configuration. The current behavior is merge.

If merge is the expected behavior then before making [this validation](https://github.com/opensearch-project/ml-commons/blob/9aea9a08ef2d9eba082bc34382a8a04c1cc5bffa/plugin/src/main/java/org/opensearch/ml/action/connector/UpdateConnectorTransportAction.java#L94), we may need to merge parameters.

**What is your host/environment?**
 - OS: MacOS
 - Version: 2.14
 - Plugins: ml-commons

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment] 2024-07-01 16:10
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

Thanks for reporting this bug.

**Comment by Zhangxunmt** [comment] 2024-07-29 22:12
This is not a bug since the behavior is expected. In the current Update Connector API, the parameters in the update request body will override the existing ones in the connector so some parameters can be deleted. However, I do think we should tune this a bit to merge rather than replacing the whole parameters, as I fixed in this https://github.com/opensearch-project/ml-commons/pull/2784.

**Closed** 2024-07-30 18:14 UTC
Labels: bug
