### ISSUE TITLE
[BUG] Search for tasks returns 404 "index not found"

### ISSUE THREAD

**Issue by samuel-oci** [opensearch-project/ml-commons#1880] opened 2024-01-17 01:29 UTC
**What is the bug?**
When searching for tasks before creating the first one, we are getting a 404 exception of `index not found`
Similar to https://github.com/opensearch-project/ml-commons/issues/1787 we should avoid exposing internal implementation and just return empty search results which is what the expected behavior should be.

**How can one reproduce the bug?**
1.Run POST GET /_plugins/_ml/tasks/_search before model group is created
2.Returns 404 error :
An error occurred while initializing cluster bootstrap: NotFoundError(404, 'index_not_found_exception', 'no such index [.plugins-ml-task]', .plugins-ml-task, index_or_alias)

**What is the expected behavior?**
Return empty search results

**What is your host/environment?**
 - OS: Mac OS X
 - Version: OpenSearch 2.11
 - Plugins: ml-commons

**Comment by saratvemulapalli** [comment] 2024-01-17 20:58
Duplicate of https://github.com/opensearch-project/ml-commons/issues/1878

**Comment by saratvemulapalli** [comment] 2024-01-17 21:27
Re-opening this. Looks like others are for model groups, model and this is for tasks.

**Closed** 2024-01-19 21:55 UTC
Labels: bug, untriaged
