### ISSUE TITLE
[BUG] Race condition, deleting connector immediately after deleting model fails

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/ml-commons#1567] opened 2023-10-30 19:22 UTC
**What is the bug?**
We built a pipeline that allows us to undeploy a model, delete it, and then delete the related connector. When we run this we get the status that the model has undeployed, it has deleted successfully, then finally when it gets to the connector, it fails because the connector still believes the model exists. 

We've run this pipeline several times and it seems like the model is consistently reporting it's been deleted but from the connectors perspective it has not yet. 

**How can one reproduce the bug?**
Create connector, model, and attempt to undeploy, it delete the model, and then the connector programatically. 

**What is the expected behavior?**
Model should not report it's been deleted until it has been completely removed such that the connector will not think it has persisted. 

**What is your host/environment?**
Docker with a single node cluster. OpenSearch 2.11

**Comment by ylwu-amzn** [comment] 2023-11-03 16:20
Xun , can you help take a look

**Comment by Zhangxunmt** [comment] 2023-11-03 17:36
This one looks interesting. Will look into it today.

**Comment by Zhangxunmt** [comment] 2023-11-21 00:16
This cannot be reproduced locally in my 2.11 cluster. I created connector A, and a remote model B referencing to the connector A. A cannot be deleted unless B is un-deployed and deleted. Immediately after I delete B, A can be deleted successfully.

All the above was done through the rest APIs. So my guess is that you code runs faster than the OS delete process. Can you wait a little bit (maybe only 0.5s) before deleting your connector in your pipeline? It looks inept to setup this waiting time in Ml-Common delete process since we don't know when the delete is executed after "XYZ" previous operations. @dtaivpp

**Comment by Zhangxunmt** [comment] 2023-11-28 20:19
Closing this issue if no more comments from @dtaivpp .

**Closed** 2023-11-28 22:09 UTC
Labels: help wanted, discuss
